-- Auto-generated by scripts/gen_mock_indicators_seed.py — DO NOT hand-edit values.
-- Gap-filling DEMO values for non-binding indicators P-a/P-c/P-d/P-f.
-- NEVER read by the verdict/composition path (see 0025_mock_indicators.sql).
-- Idempotent: wipe all demo mock rows, then upsert fresh.
DELETE FROM skolske_obvody.mock_indicators WHERE is_demo = true;

INSERT INTO skolske_obvody.mock_indicators
  (district_id, condition_code, display_value, detail, source_gap, is_demo)
VALUES
  ('45b113f3-3614-46ed-b9bf-67289a306670', 'Pa', $v$82 % obsadenosť$v$, $v${"capacity": 400, "students_est": 328, "occupancy_pct": 82, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('45b113f3-3614-46ed-b9bf-67289a306670', 'Pc', $v$23 min, 0 prestupov$v$, $v${"duration_min": 23, "transfers": 0, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('45b113f3-3614-46ed-b9bf-67289a306670', 'Pd', $v$1 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 1, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('45b113f3-3614-46ed-b9bf-67289a306670', 'Pf', $v$~210 detí 0–6 r., ŠVVP 7 %$v$, $v${"children_0_6_est": 210, "trend_5y_pct": 2, "svvp_pct": 7}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('689f1541-6fb4-4ee6-958c-c4cc09e5a1ff', 'Pa', $v$77 % obsadenosť$v$, $v${"capacity": 460, "students_est": 354, "occupancy_pct": 77, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('689f1541-6fb4-4ee6-958c-c4cc09e5a1ff', 'Pc', $v$19 min, 1 prestup$v$, $v${"duration_min": 19, "transfers": 1, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('689f1541-6fb4-4ee6-958c-c4cc09e5a1ff', 'Pd', $v$2 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 2, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('689f1541-6fb4-4ee6-958c-c4cc09e5a1ff', 'Pf', $v$~360 detí 0–6 r., ŠVVP 8 %$v$, $v${"children_0_6_est": 360, "trend_5y_pct": -3, "svvp_pct": 8}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('c6c4180a-871c-42fc-b74b-29e0a693b122', 'Pa', $v$89 % obsadenosť$v$, $v${"capacity": 580, "students_est": 516, "occupancy_pct": 89, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('c6c4180a-871c-42fc-b74b-29e0a693b122', 'Pc', $v$12 min, 0 prestupov$v$, $v${"duration_min": 12, "transfers": 0, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('c6c4180a-871c-42fc-b74b-29e0a693b122', 'Pd', $v$1 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 1, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('c6c4180a-871c-42fc-b74b-29e0a693b122', 'Pf', $v$~250 detí 0–6 r., ŠVVP 11 %$v$, $v${"children_0_6_est": 250, "trend_5y_pct": 1, "svvp_pct": 11}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('7e0dd639-cf90-463f-8473-34541bddecf1', 'Pa', $v$65 % obsadenosť$v$, $v${"capacity": 480, "students_est": 312, "occupancy_pct": 65, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('7e0dd639-cf90-463f-8473-34541bddecf1', 'Pc', $v$10 min, 2 prestupy$v$, $v${"duration_min": 10, "transfers": 2, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('7e0dd639-cf90-463f-8473-34541bddecf1', 'Pd', $v$5 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 5, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('7e0dd639-cf90-463f-8473-34541bddecf1', 'Pf', $v$~320 detí 0–6 r., ŠVVP 12 %$v$, $v${"children_0_6_est": 320, "trend_5y_pct": 0, "svvp_pct": 12}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('cdf8f0b5-f66e-4438-8f7a-48ac656443bf', 'Pa', $v$80 % obsadenosť$v$, $v${"capacity": 400, "students_est": 320, "occupancy_pct": 80, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('cdf8f0b5-f66e-4438-8f7a-48ac656443bf', 'Pc', $v$21 min, 0 prestupov$v$, $v${"duration_min": 21, "transfers": 0, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('cdf8f0b5-f66e-4438-8f7a-48ac656443bf', 'Pd', $v$3 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 3, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('cdf8f0b5-f66e-4438-8f7a-48ac656443bf', 'Pf', $v$~210 detí 0–6 r., ŠVVP 10 %$v$, $v${"children_0_6_est": 210, "trend_5y_pct": -1, "svvp_pct": 10}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('d15e65c7-7a0b-4e9d-bb6f-3b5f9667a8b5', 'Pa', $v$79 % obsadenosť$v$, $v${"capacity": 480, "students_est": 379, "occupancy_pct": 79, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('d15e65c7-7a0b-4e9d-bb6f-3b5f9667a8b5', 'Pc', $v$26 min, 2 prestupy$v$, $v${"duration_min": 26, "transfers": 2, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('d15e65c7-7a0b-4e9d-bb6f-3b5f9667a8b5', 'Pd', $v$2 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 2, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('d15e65c7-7a0b-4e9d-bb6f-3b5f9667a8b5', 'Pf', $v$~140 detí 0–6 r., ŠVVP 4 %$v$, $v${"children_0_6_est": 140, "trend_5y_pct": 2, "svvp_pct": 4}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('022b88de-8f54-43fd-9a37-b165102db9f8', 'Pa', $v$79 % obsadenosť$v$, $v${"capacity": 520, "students_est": 411, "occupancy_pct": 79, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('022b88de-8f54-43fd-9a37-b165102db9f8', 'Pc', $v$13 min, 0 prestupov$v$, $v${"duration_min": 13, "transfers": 0, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('022b88de-8f54-43fd-9a37-b165102db9f8', 'Pd', $v$1 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 1, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('022b88de-8f54-43fd-9a37-b165102db9f8', 'Pf', $v$~280 detí 0–6 r., ŠVVP 5 %$v$, $v${"children_0_6_est": 280, "trend_5y_pct": 3, "svvp_pct": 5}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('6f4bee27-013c-4937-8dd7-73f3a28a7118', 'Pa', $v$73 % obsadenosť$v$, $v${"capacity": 440, "students_est": 321, "occupancy_pct": 73, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('6f4bee27-013c-4937-8dd7-73f3a28a7118', 'Pc', $v$25 min, 1 prestup$v$, $v${"duration_min": 25, "transfers": 1, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('6f4bee27-013c-4937-8dd7-73f3a28a7118', 'Pd', $v$1 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 1, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('6f4bee27-013c-4937-8dd7-73f3a28a7118', 'Pf', $v$~340 detí 0–6 r., ŠVVP 7 %$v$, $v${"children_0_6_est": 340, "trend_5y_pct": 0, "svvp_pct": 7}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('d3cae810-c461-429f-86d9-0be4474ddc2c', 'Pa', $v$78 % obsadenosť$v$, $v${"capacity": 380, "students_est": 296, "occupancy_pct": 78, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('d3cae810-c461-429f-86d9-0be4474ddc2c', 'Pc', $v$20 min, 2 prestupy$v$, $v${"duration_min": 20, "transfers": 2, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('d3cae810-c461-429f-86d9-0be4474ddc2c', 'Pd', $v$0 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 0, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('d3cae810-c461-429f-86d9-0be4474ddc2c', 'Pf', $v$~290 detí 0–6 r., ŠVVP 9 %$v$, $v${"children_0_6_est": 290, "trend_5y_pct": 2, "svvp_pct": 9}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('cddfee4e-fb1d-48c1-bbb5-2626ae415f87', 'Pa', $v$92 % obsadenosť$v$, $v${"capacity": 440, "students_est": 405, "occupancy_pct": 92, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('cddfee4e-fb1d-48c1-bbb5-2626ae415f87', 'Pc', $v$11 min, 2 prestupy$v$, $v${"duration_min": 11, "transfers": 2, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('cddfee4e-fb1d-48c1-bbb5-2626ae415f87', 'Pd', $v$4 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 4, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('cddfee4e-fb1d-48c1-bbb5-2626ae415f87', 'Pf', $v$~350 detí 0–6 r., ŠVVP 4 %$v$, $v${"children_0_6_est": 350, "trend_5y_pct": 2, "svvp_pct": 4}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('9f1e3d72-5246-4414-9340-bccc2d6036d0', 'Pa', $v$75 % obsadenosť$v$, $v${"capacity": 460, "students_est": 345, "occupancy_pct": 75, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('9f1e3d72-5246-4414-9340-bccc2d6036d0', 'Pc', $v$15 min, 1 prestup$v$, $v${"duration_min": 15, "transfers": 1, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('9f1e3d72-5246-4414-9340-bccc2d6036d0', 'Pd', $v$3 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 3, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('9f1e3d72-5246-4414-9340-bccc2d6036d0', 'Pf', $v$~320 detí 0–6 r., ŠVVP 8 %$v$, $v${"children_0_6_est": 320, "trend_5y_pct": 0, "svvp_pct": 8}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true),
  ('61724cfb-2093-4f19-a47e-92b0b7e12429', 'Pa', $v$69 % obsadenosť$v$, $v${"capacity": 540, "students_est": 373, "occupancy_pct": 69, "unit": "%"}$v$::jsonb, $v$EDUZBER kapacita budov nedostupná$v$, true),
  ('61724cfb-2093-4f19-a47e-92b0b7e12429', 'Pc', $v$9 min, 1 prestup$v$, $v${"duration_min": 9, "transfers": 1, "scenario": "ráno 07:30, pondelok"}$v$::jsonb, $v$Agentúrne GTFS / Google Routes kľúč nedostupný$v$, true),
  ('61724cfb-2093-4f19-a47e-92b0b7e12429', 'Pd', $v$0 % dopyt po menšinovom jazyku$v$, $v${"minority_demand_pct": 0, "school_language": "SK", "unit": "%"}$v$::jsonb, $v$Dataset jazykového nároku (CVTI/RÚŠS) nedostupný$v$, true),
  ('61724cfb-2093-4f19-a47e-92b0b7e12429', 'Pf', $v$~230 detí 0–6 r., ŠVVP 11 %$v$, $v${"children_0_6_est": 230, "trend_5y_pct": -1, "svvp_pct": 11}$v$::jsonb, $v$Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné$v$, true)
ON CONFLICT (district_id, condition_code) DO UPDATE SET
  display_value = EXCLUDED.display_value,
  detail        = EXCLUDED.detail,
  source_gap    = EXCLUDED.source_gap,
  is_demo       = EXCLUDED.is_demo;
