"""
Generate scripts/sql/mock_indicators_seed.sql — QA bod 5/9 gap-filling DEMO data.

Produces PLAUSIBLE, internally-consistent (deterministic, hash-derived — not
random noise) mock values for the four secondary / non-binding § 44 indicators
that are stuck on a data GAP across all 12 Prešov districts:

  P-a  capacity / occupancy    (EDUZBER gap)
  P-c  MHD transit access      (no GTFS / Routes key)
  P-d  language-rights demand  (jazykový nárok gap)
  P-f  child demographics+ŠVVP (ŠTATSR / CVTI gap)

These values are display-only. They are written to skolske_obvody.mock_indicators
and surfaced via public.so_mock_indicators, which the verdict/composition path
NEVER reads (see scripts/sql/0025_mock_indicators.sql header). Re-run after a
districts refresh; the seed is idempotent.

Usage:
    python3 scripts/gen_mock_indicators_seed.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "sql" / "mock_indicators_seed.sql"

# 12 Prešov districts (id pinned to the live DB).
DISTRICTS = [
    ("45b113f3-3614-46ed-b9bf-67289a306670", "ZŠ s MŠ, Námestie Kráľovnej pokoja 4"),
    ("689f1541-6fb4-4ee6-958c-c4cc09e5a1ff", "ZŠ, Bajkalská č. 29"),
    ("c6c4180a-871c-42fc-b74b-29e0a693b122", "ZŠ, Československej armády č. 22"),
    ("7e0dd639-cf90-463f-8473-34541bddecf1", "ZŠ, Kúpeľná č. 2"),
    ("cdf8f0b5-f66e-4438-8f7a-48ac656443bf", "ZŠ, Lesnícka č. 1"),
    ("d15e65c7-7a0b-4e9d-bb6f-3b5f9667a8b5", "ZŠ, Májové námestie č. 1"),
    ("022b88de-8f54-43fd-9a37-b165102db9f8", "ZŠ, Mirka Nešpora č. 2"),
    ("6f4bee27-013c-4937-8dd7-73f3a28a7118", "ZŠ, Prostějovská č. 38"),
    ("d3cae810-c461-429f-86d9-0be4474ddc2c", "ZŠ, Sibírska č. 42"),
    ("cddfee4e-fb1d-48c1-bbb5-2626ae415f87", "ZŠ, Šmeralova č. 25"),
    ("9f1e3d72-5246-4414-9340-bccc2d6036d0", "ZŠ, Šrobárova č. 20"),
    ("61724cfb-2093-4f19-a47e-92b0b7e12429", "ZŠ, Važecká č. 11"),
]


def _h(did: str, salt: str) -> int:
    return int(hashlib.sha256((did + salt).encode()).hexdigest(), 16)


def _prestup_word(n: int) -> str:
    # Slovak count grammar: 0/5+ = prestupov, 1 = prestup, 2–4 = prestupy
    if n == 1:
        return "prestup"
    if 2 <= n <= 4:
        return "prestupy"
    return "prestupov"


def build_rows() -> list[tuple]:
    rows: list[tuple] = []
    for did, _name in DISTRICTS:
        # --- P-a: capacity / occupancy (consistent: students = capacity * occ%) ---
        capacity = 320 + (_h(did, "cap") % 14) * 20            # 320..580, step 20
        occ_pct = 62 + (_h(did, "occ") % 33)                   # 62..94 %
        students = round(capacity * occ_pct / 100)
        rows.append((did, "Pa",
                     f"{occ_pct} % obsadenosť",
                     {"capacity": capacity, "students_est": students,
                      "occupancy_pct": occ_pct, "unit": "%"},
                     "EDUZBER kapacita budov nedostupná"))

        # --- P-c: MHD transit (morning scenario) ---
        dur = 9 + (_h(did, "dur") % 19)                        # 9..27 min
        transfers = _h(did, "trf") % 3                         # 0..2
        rows.append((did, "Pc",
                     f"{dur} min, {transfers} {_prestup_word(transfers)}",
                     {"duration_min": dur, "transfers": transfers,
                      "scenario": "ráno 07:30, pondelok"},
                     "Agentúrne GTFS / Google Routes kľúč nedostupný"))

        # --- P-d: minority-language demand share (Prešov is SK-majority) ---
        minority_pct = _h(did, "lang") % 6                     # 0..5 %
        rows.append((did, "Pd",
                     f"{minority_pct} % dopyt po menšinovom jazyku",
                     {"minority_demand_pct": minority_pct,
                      "school_language": "SK", "unit": "%"},
                     "Dataset jazykového nároku (CVTI/RÚŠS) nedostupný"))

        # --- P-f: child demographics + ŠVVP share ---
        children = 140 + (_h(did, "kids") % 23) * 10           # 140..360
        trend = -3 + (_h(did, "trend") % 8)                    # -3..+4 % / 5y
        svvp_pct = 4 + (_h(did, "svvp") % 9)                   # 4..12 %
        rows.append((did, "Pf",
                     f"~{children} detí 0–6 r., ŠVVP {svvp_pct} %",
                     {"children_0_6_est": children, "trend_5y_pct": trend,
                      "svvp_pct": svvp_pct},
                     "Demografia ŠTATSR + ŠVVP CVTI/RÚŠS nedostupné"))
    return rows


def render_sql(rows: list[tuple]) -> str:
    def s(x: str) -> str:
        return x.replace("'", "''")

    lines = [
        "-- Auto-generated by scripts/gen_mock_indicators_seed.py — DO NOT hand-edit values.",
        "-- Gap-filling DEMO values for non-binding indicators P-a/P-c/P-d/P-f.",
        "-- NEVER read by the verdict/composition path (see 0025_mock_indicators.sql).",
        "-- Idempotent: wipe all demo mock rows, then upsert fresh.",
        "DELETE FROM skolske_obvody.mock_indicators WHERE is_demo = true;",
        "",
        "INSERT INTO skolske_obvody.mock_indicators",
        "  (district_id, condition_code, display_value, detail, source_gap, is_demo)",
        "VALUES",
    ]
    vals = []
    for did, code, disp, detail, gap in rows:
        dj = json.dumps(detail, ensure_ascii=False)
        vals.append(
            f"  ('{did}', '{code}', $v${s(disp)}$v$, "
            f"$v${dj}$v$::jsonb, $v${s(gap)}$v$, true)"
        )
    lines.append(",\n".join(vals))
    lines += [
        "ON CONFLICT (district_id, condition_code) DO UPDATE SET",
        "  display_value = EXCLUDED.display_value,",
        "  detail        = EXCLUDED.detail,",
        "  source_gap    = EXCLUDED.source_gap,",
        "  is_demo       = EXCLUDED.is_demo;",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    rows = build_rows()
    OUT.write_text(render_sql(rows), encoding="utf-8")
    print(f"[gen_mock_indicators_seed] wrote {len(rows)} rows "
          f"({len(DISTRICTS)} districts × 4 indicators) to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
