#!/usr/bin/env python3
"""
Render Sprint C seed SQL from composition fixtures.

Usage:
    python3 scripts/render_seed_sprint_c.py > tests/fixtures/seed_sprint_c.sql

Reads tests/fixtures/composition.json and generates deterministic SQL INSERT
statements for the staging DB. Also adds:
  - 1 municipality Prešov (slug='presov')
  - 1 municipality Košice (for scope isolation test — must NOT appear in views)
  - 1 Košice district + verdict + finding (scope isolation canary)
  - Per Prešov district: 1 schools row, 1 verdicts row per condition code
  - evidence_text with embedded email, phone, RČ for sanitization tests
  - provenance with allowlisted + non-allowlisted URLs for allowlist tests
"""

from __future__ import annotations

import json
import os
import sys
import uuid

FIXTURES_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "tests", "fixtures", "composition.json",
)

NAMESPACE = uuid.UUID("00000000-0000-0000-0000-000000000001")

# Fixed UUIDs for seed determinism
PRESOV_MUN_ID = str(uuid.uuid5(NAMESPACE, "municipality_presov"))
KOSICE_MUN_ID = str(uuid.uuid5(NAMESPACE, "municipality_kosice"))
KOSICE_SCHOOL_ID = str(uuid.uuid5(NAMESPACE, "school_kosice_seed"))
KOSICE_DISTRICT_ID = str(uuid.uuid5(NAMESPACE, "district_kosice_seed"))

ENGINE_VERSION = "seed_sprint_c_v1"
METHODOLOGY_VERSION = "0.1"
DATASET_VERSION = "seed_sprint_c"

# Condition codes and values for seeding (per district)
CONDITION_CODES = ["S1", "S2", "S3", "Pa", "Pb", "Pc", "Pd", "Pe", "Pf"]

# Evidence text with PII for sanitization test
EVIDENCE_WITH_PII = (
    "Kontakt: jan.novak@mestopresov.sk, tel: +421 905 123 456, "
    "RČ: 900101/1234. Obvod spĺňa podmienky § 44."
)
EVIDENCE_CLEAN = "Toto je čistý dôkaz bez citlivých údajov."

# Provenance sources for allowlist test
ALLOWLISTED_SOURCE = "https://slov-lex.sk/pravne-predpisy/SK/ZZ/2003/596"
NON_ALLOWLISTED_SOURCE = "http://internal.local/secret-analysis"


def sql_str(s: str) -> str:
    """Escape string for SQL dollar-quote."""
    return s.replace("$", "\\$")


def main() -> None:
    with open(FIXTURES_PATH) as f:
        fixtures = json.load(f)

    presov_fixtures = [x for x in fixtures if x["kind"] in ("real", "real_placeholder")]
    synthetic_fixtures = [x for x in fixtures if x["kind"] == "synthetic"]

    lines = []
    lines.append("-- Sprint C seed SQL — generated by scripts/render_seed_sprint_c.py")
    lines.append("-- DO NOT EDIT MANUALLY — regenerate with: python3 scripts/render_seed_sprint_c.py")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    # Schema
    lines.append("CREATE SCHEMA IF NOT EXISTS skolske_obvody;")
    lines.append("")

    # Municipalities
    lines.append("-- Municipalities")
    lines.append(f"""INSERT INTO skolske_obvody.municipalities (id, name, slug) VALUES
  ('{PRESOV_MUN_ID}', 'Prešov', 'presov'),
  ('{KOSICE_MUN_ID}', 'Košice', 'kosice')
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name;""")
    lines.append("")

    # Schools for Prešov districts
    lines.append("-- Schools (one per district)")
    school_inserts = []
    school_id_map: dict[str, str] = {}
    for fx in presov_fixtures + synthetic_fixtures:
        school_id = str(uuid.uuid5(NAMESPACE, f"school_{fx['district_id']}"))
        school_id_map[fx["district_id"]] = school_id
        school_name = "ZŠ " + fx["name"][:40]
        school_inserts.append(
            f"  ('{school_id}', '{school_name}', 'zs', 200, 'sk', NULL)"
        )
    # Košice school
    school_inserts.append(
        f"  ('{KOSICE_SCHOOL_ID}', 'ZŠ Košice seed', 'zs', 150, 'sk', NULL)"
    )
    lines.append(
        "INSERT INTO skolske_obvody.schools (id, name, type, student_count, teaching_language, geom)\nVALUES\n"
        + ",\n".join(school_inserts)
        + "\nON CONFLICT (id) DO NOTHING;"
    )
    lines.append("")

    # Districts — Prešov
    lines.append("-- Districts (Prešov)")
    district_inserts = []
    for fx in presov_fixtures + synthetic_fixtures:
        school_id = school_id_map[fx["district_id"]]
        safe_name = fx["name"][:60].replace("'", "''")
        district_inserts.append(
            f"  ('{fx['district_id']}', '{safe_name}', "
            f"'{PRESOV_MUN_ID}', '{school_id}', 'estimated', NULL)"
        )
    lines.append(
        "INSERT INTO skolske_obvody.districts (id, name, municipality_id, school_id, geometry_confidence, geom)\nVALUES\n"
        + ",\n".join(district_inserts)
        + "\nON CONFLICT (id) DO NOTHING;"
    )
    lines.append("")

    # Košice district (scope isolation canary)
    lines.append("-- Košice district (scope isolation canary)")
    lines.append(
        f"INSERT INTO skolske_obvody.districts (id, name, municipality_id, school_id, geometry_confidence, geom) VALUES\n"
        f"  ('{KOSICE_DISTRICT_ID}', 'Košice canary district', '{KOSICE_MUN_ID}', '{KOSICE_SCHOOL_ID}', 'estimated', NULL)\n"
        f"ON CONFLICT (id) DO NOTHING;"
    )
    lines.append("")

    # Verdicts — for all Prešov districts (using fixture verdicts if available, else synthesize)
    lines.append("-- Verdicts (Prešov districts)")
    all_presov = presov_fixtures + synthetic_fixtures
    for fx in all_presov:
        district_id = fx["district_id"]
        verdicts = fx.get("verdicts", {})
        is_illustrative_map = fx.get("is_illustrative", {})

        # If no verdicts, skip (district will have NONE composition)
        if not verdicts:
            continue

        # Use PII evidence for first district, clean for rest (sanitization test)
        use_pii = (fx == all_presov[0])
        # Use non-allowlisted provenance for second district, allowlisted for rest
        use_non_allowlist = (fx == all_presov[1])

        for code in CONDITION_CODES:
            value = verdicts.get(code, "PASS")
            is_illustr = is_illustrative_map.get(code, False)
            vid = str(uuid.uuid5(NAMESPACE, f"verdict_{district_id}_{code}"))
            evid_text = EVIDENCE_WITH_PII if use_pii else EVIDENCE_CLEAN
            prov_source = NON_ALLOWLISTED_SOURCE if use_non_allowlist else ALLOWLISTED_SOURCE

            lines.append(f"""INSERT INTO skolske_obvody.verdicts (
  id, district_id, condition_code, value, confidence, data_completeness,
  provenance, methodology, is_illustrative, is_proxy, is_mock,
  dataset_version, methodology_version, engine_version, computed_at,
  evidence_text, evidence_refs
) VALUES (
  '{vid}', '{district_id}', '{code}', '{value}',
  0.8, 0.9,
  '{{"source": "{prov_source}", "fetched_at": "2026-06-24T10:00:00Z"}}'::jsonb,
  '{{"rule": "{code} methodology rule"}}'::jsonb,
  {'TRUE' if is_illustr else 'FALSE'}, FALSE, FALSE,
  '{DATASET_VERSION}', '{METHODOLOGY_VERSION}', '{ENGINE_VERSION}',
  NOW(),
  $seed${evid_text}$seed$,
  '[]'::jsonb
) ON CONFLICT (district_id, condition_code, engine_version)
DO UPDATE SET value = EXCLUDED.value, evidence_text = EXCLUDED.evidence_text;""")

    lines.append("")

    # Košice verdict (scope isolation canary)
    lines.append("-- Košice verdict (scope isolation canary)")
    kosice_vid = str(uuid.uuid5(NAMESPACE, f"verdict_{KOSICE_DISTRICT_ID}_S1"))
    lines.append(f"""INSERT INTO skolske_obvody.verdicts (
  id, district_id, condition_code, value, confidence, data_completeness,
  provenance, methodology, is_illustrative, is_proxy, is_mock,
  dataset_version, methodology_version, engine_version, computed_at,
  evidence_text, evidence_refs
) VALUES (
  '{kosice_vid}', '{KOSICE_DISTRICT_ID}', 'S1', 'PASS',
  0.8, 0.9,
  '{{"source": "https://kosice.sk/data"}}'::jsonb,
  '{{"rule": "S1 methodology rule"}}'::jsonb,
  FALSE, FALSE, FALSE,
  '{DATASET_VERSION}', '{METHODOLOGY_VERSION}', '{ENGINE_VERSION}',
  NOW(),
  $seed$Košice canary verdict$seed$,
  '[]'::jsonb
) ON CONFLICT (district_id, condition_code, engine_version) DO UPDATE SET value = EXCLUDED.value;""")
    lines.append("")

    # Findings for first Prešov district
    lines.append("-- Findings (sample for first Prešov district)")
    if all_presov:
        fx = all_presov[0]
        fid = str(uuid.uuid5(NAMESPACE, f"finding_{fx['district_id']}_S1"))
        vid = str(uuid.uuid5(NAMESPACE, f"verdict_{fx['district_id']}_S1"))
        lines.append(f"""INSERT INTO skolske_obvody.findings (
  id, verdict_id, district_id, municipality_id, condition_code,
  severity, status, evidence_text, engine_version, created_at
) VALUES (
  '{fid}', '{vid}', '{fx['district_id']}', '{PRESOV_MUN_ID}',
  'S1', 'medium', 'open',
  $seed${EVIDENCE_WITH_PII}$seed$,
  '{ENGINE_VERSION}', NOW()
) ON CONFLICT (district_id, condition_code, engine_version)
DO UPDATE SET evidence_text = EXCLUDED.evidence_text;""")
    lines.append("")

    # Košice finding (scope isolation canary)
    lines.append("-- Košice finding (scope isolation canary)")
    kosice_fid = str(uuid.uuid5(NAMESPACE, f"finding_{KOSICE_DISTRICT_ID}_S1"))
    lines.append(f"""INSERT INTO skolske_obvody.findings (
  id, verdict_id, district_id, municipality_id, condition_code,
  severity, status, evidence_text, engine_version, created_at
) VALUES (
  '{kosice_fid}', '{kosice_vid}', '{KOSICE_DISTRICT_ID}', '{KOSICE_MUN_ID}',
  'S1', 'info', 'open',
  $seed$Košice canary finding$seed$,
  '{ENGINE_VERSION}', NOW()
) ON CONFLICT (district_id, condition_code, engine_version) DO UPDATE SET evidence_text = EXCLUDED.evidence_text;""")
    lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    lines.append(f"-- Seed constants (for test assertions):")
    lines.append(f"-- PRESOV_MUN_ID = '{PRESOV_MUN_ID}'")
    lines.append(f"-- KOSICE_MUN_ID = '{KOSICE_MUN_ID}'")
    lines.append(f"-- ENGINE_VERSION = '{ENGINE_VERSION}'")
    lines.append(f"-- Total presov districts seeded: {len(all_presov)}")
    lines.append(f"-- Total presov verdicts seeded: ~{sum(1 for fx in all_presov if fx.get('verdicts')) * len(CONDITION_CODES)}")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
